/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CarbonSealRegistry {
  export type FarmStruct = {
    farmId: BigNumberish;
    farmer: AddressLike;
    name: string;
    area: BigNumberish;
    location: string;
    soilType: string;
    totalCarbon: BigNumberish;
    carbonDebt: BigNumberish;
    lastReadingTimestamp: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type FarmStructOutput = [
    farmId: bigint,
    farmer: string,
    name: string,
    area: bigint,
    location: string,
    soilType: string,
    totalCarbon: bigint,
    carbonDebt: bigint,
    lastReadingTimestamp: bigint,
    isActive: boolean,
    createdAt: bigint
  ] & {
    farmId: bigint;
    farmer: string;
    name: string;
    area: bigint;
    location: string;
    soilType: string;
    totalCarbon: bigint;
    carbonDebt: bigint;
    lastReadingTimestamp: bigint;
    isActive: boolean;
    createdAt: bigint;
  };

  export type CarbonReadingStruct = {
    readingId: BigNumberish;
    farmId: BigNumberish;
    amount: BigNumberish;
    source: string;
    verificationHash: string;
    timestamp: BigNumberish;
    verifiedBy: AddressLike;
  };

  export type CarbonReadingStructOutput = [
    readingId: bigint,
    farmId: bigint,
    amount: bigint,
    source: string,
    verificationHash: string,
    timestamp: bigint,
    verifiedBy: string
  ] & {
    readingId: bigint;
    farmId: bigint;
    amount: bigint;
    source: string;
    verificationHash: string;
    timestamp: bigint;
    verifiedBy: string;
  };
}

export interface CarbonSealRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MIN_CARBON_TO_MINT"
      | "ORACLE_ROLE"
      | "PRECISION"
      | "VERIFIER_ROLE"
      | "activateFarm"
      | "addCarbonReading"
      | "addCarbonReadingsBatch"
      | "addCreditToFarm"
      | "addressToFarmId"
      | "deactivateFarm"
      | "farmCounter"
      | "farmCredits"
      | "farmReadings"
      | "farms"
      | "getActiveFarmers"
      | "getAvailableCarbon"
      | "getFarmByAddress"
      | "getFarmStats"
      | "getRecentReadings"
      | "getRoleAdmin"
      | "getTotalFarms"
      | "grantRole"
      | "hasRole"
      | "readingCounter"
      | "registerFarm"
      | "renounceRole"
      | "revokeRole"
      | "setTokenContract"
      | "supportsInterface"
      | "tokenContract"
      | "updateCarbonDebt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CarbonAdded"
      | "CarbonDebtUpdated"
      | "FarmRegistered"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CARBON_TO_MINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateFarm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addCarbonReading",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addCarbonReadingsBatch",
    values: [BigNumberish, BigNumberish[], string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addCreditToFarm",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToFarmId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateFarm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "farmCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmCredits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "farmReadings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "farms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getActiveFarmers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableCarbon",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFarmByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFarmStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentReadings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalFarms",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "readingCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerFarm",
    values: [string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCarbonDebt",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CARBON_TO_MINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCarbonReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCarbonReadingsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCreditToFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToFarmId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmReadings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "farms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveFarmers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableCarbon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFarmByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFarmStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentReadings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalFarms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "readingCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCarbonDebt",
    data: BytesLike
  ): Result;
}

export namespace CarbonAddedEvent {
  export type InputTuple = [
    farmId: BigNumberish,
    readingId: BigNumberish,
    amount: BigNumberish,
    source: string,
    verificationHash: string
  ];
  export type OutputTuple = [
    farmId: bigint,
    readingId: bigint,
    amount: bigint,
    source: string,
    verificationHash: string
  ];
  export interface OutputObject {
    farmId: bigint;
    readingId: bigint;
    amount: bigint;
    source: string;
    verificationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarbonDebtUpdatedEvent {
  export type InputTuple = [
    farmId: BigNumberish,
    newDebt: BigNumberish,
    availableCarbon: BigNumberish
  ];
  export type OutputTuple = [
    farmId: bigint,
    newDebt: bigint,
    availableCarbon: bigint
  ];
  export interface OutputObject {
    farmId: bigint;
    newDebt: bigint;
    availableCarbon: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FarmRegisteredEvent {
  export type InputTuple = [
    farmer: AddressLike,
    farmId: BigNumberish,
    name: string,
    area: BigNumberish,
    location: string
  ];
  export type OutputTuple = [
    farmer: string,
    farmId: bigint,
    name: string,
    area: bigint,
    location: string
  ];
  export interface OutputObject {
    farmer: string;
    farmId: bigint;
    name: string;
    area: bigint;
    location: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonSealRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonSealRegistry;
  waitForDeployment(): Promise<this>;

  interface: CarbonSealRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MIN_CARBON_TO_MINT: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  activateFarm: TypedContractMethod<
    [_farmId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addCarbonReading: TypedContractMethod<
    [
      _farmId: BigNumberish,
      _amount: BigNumberish,
      _source: string,
      _verificationHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  addCarbonReadingsBatch: TypedContractMethod<
    [
      _farmId: BigNumberish,
      _amounts: BigNumberish[],
      _sources: string[],
      _verificationHashes: string[]
    ],
    [bigint[]],
    "nonpayable"
  >;

  addCreditToFarm: TypedContractMethod<
    [_farmId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addressToFarmId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deactivateFarm: TypedContractMethod<
    [_farmId: BigNumberish],
    [void],
    "nonpayable"
  >;

  farmCounter: TypedContractMethod<[], [bigint], "view">;

  farmCredits: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  farmReadings: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint, string] & {
        readingId: bigint;
        farmId: bigint;
        amount: bigint;
        source: string;
        verificationHash: string;
        timestamp: bigint;
        verifiedBy: string;
      }
    ],
    "view"
  >;

  farms: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        farmId: bigint;
        farmer: string;
        name: string;
        area: bigint;
        location: string;
        soilType: string;
        totalCarbon: bigint;
        carbonDebt: bigint;
        lastReadingTimestamp: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getActiveFarmers: TypedContractMethod<[], [string[]], "view">;

  getAvailableCarbon: TypedContractMethod<
    [_farmId: BigNumberish],
    [bigint],
    "view"
  >;

  getFarmByAddress: TypedContractMethod<
    [_farmer: AddressLike],
    [CarbonSealRegistry.FarmStructOutput],
    "view"
  >;

  getFarmStats: TypedContractMethod<
    [_farmId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCarbon: bigint;
        carbonDebt: bigint;
        availableCarbon: bigint;
        readingCount: bigint;
        creditCount: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;

  getRecentReadings: TypedContractMethod<
    [_farmId: BigNumberish, _count: BigNumberish],
    [CarbonSealRegistry.CarbonReadingStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalFarms: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  readingCounter: TypedContractMethod<[], [bigint], "view">;

  registerFarm: TypedContractMethod<
    [_name: string, _area: BigNumberish, _location: string, _soilType: string],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenContract: TypedContractMethod<
    [_tokenContract: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tokenContract: TypedContractMethod<[], [string], "view">;

  updateCarbonDebt: TypedContractMethod<
    [_farmId: BigNumberish, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_CARBON_TO_MINT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activateFarm"
  ): TypedContractMethod<[_farmId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addCarbonReading"
  ): TypedContractMethod<
    [
      _farmId: BigNumberish,
      _amount: BigNumberish,
      _source: string,
      _verificationHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCarbonReadingsBatch"
  ): TypedContractMethod<
    [
      _farmId: BigNumberish,
      _amounts: BigNumberish[],
      _sources: string[],
      _verificationHashes: string[]
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCreditToFarm"
  ): TypedContractMethod<
    [_farmId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addressToFarmId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateFarm"
  ): TypedContractMethod<[_farmId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "farmCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "farmCredits"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "farmReadings"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint, string] & {
        readingId: bigint;
        farmId: bigint;
        amount: bigint;
        source: string;
        verificationHash: string;
        timestamp: bigint;
        verifiedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "farms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        farmId: bigint;
        farmer: string;
        name: string;
        area: bigint;
        location: string;
        soilType: string;
        totalCarbon: bigint;
        carbonDebt: bigint;
        lastReadingTimestamp: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveFarmers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAvailableCarbon"
  ): TypedContractMethod<[_farmId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFarmByAddress"
  ): TypedContractMethod<
    [_farmer: AddressLike],
    [CarbonSealRegistry.FarmStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFarmStats"
  ): TypedContractMethod<
    [_farmId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCarbon: bigint;
        carbonDebt: bigint;
        availableCarbon: bigint;
        readingCount: bigint;
        creditCount: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentReadings"
  ): TypedContractMethod<
    [_farmId: BigNumberish, _count: BigNumberish],
    [CarbonSealRegistry.CarbonReadingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalFarms"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "readingCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerFarm"
  ): TypedContractMethod<
    [_name: string, _area: BigNumberish, _location: string, _soilType: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenContract"
  ): TypedContractMethod<[_tokenContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateCarbonDebt"
  ): TypedContractMethod<
    [_farmId: BigNumberish, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "CarbonAdded"
  ): TypedContractEvent<
    CarbonAddedEvent.InputTuple,
    CarbonAddedEvent.OutputTuple,
    CarbonAddedEvent.OutputObject
  >;
  getEvent(
    key: "CarbonDebtUpdated"
  ): TypedContractEvent<
    CarbonDebtUpdatedEvent.InputTuple,
    CarbonDebtUpdatedEvent.OutputTuple,
    CarbonDebtUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FarmRegistered"
  ): TypedContractEvent<
    FarmRegisteredEvent.InputTuple,
    FarmRegisteredEvent.OutputTuple,
    FarmRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "CarbonAdded(uint256,uint256,uint256,string,string)": TypedContractEvent<
      CarbonAddedEvent.InputTuple,
      CarbonAddedEvent.OutputTuple,
      CarbonAddedEvent.OutputObject
    >;
    CarbonAdded: TypedContractEvent<
      CarbonAddedEvent.InputTuple,
      CarbonAddedEvent.OutputTuple,
      CarbonAddedEvent.OutputObject
    >;

    "CarbonDebtUpdated(uint256,uint256,uint256)": TypedContractEvent<
      CarbonDebtUpdatedEvent.InputTuple,
      CarbonDebtUpdatedEvent.OutputTuple,
      CarbonDebtUpdatedEvent.OutputObject
    >;
    CarbonDebtUpdated: TypedContractEvent<
      CarbonDebtUpdatedEvent.InputTuple,
      CarbonDebtUpdatedEvent.OutputTuple,
      CarbonDebtUpdatedEvent.OutputObject
    >;

    "FarmRegistered(address,uint256,string,uint256,string)": TypedContractEvent<
      FarmRegisteredEvent.InputTuple,
      FarmRegisteredEvent.OutputTuple,
      FarmRegisteredEvent.OutputObject
    >;
    FarmRegistered: TypedContractEvent<
      FarmRegisteredEvent.InputTuple,
      FarmRegisteredEvent.OutputTuple,
      FarmRegisteredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
