/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICarbonSealTokenInterface extends Interface {
  getFunction(nameOrSignature: "mintCredit"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "mintCredit",
    values: [AddressLike, BigNumberish, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "mintCredit", data: BytesLike): Result;
}

export interface ICarbonSealToken extends BaseContract {
  connect(runner?: ContractRunner | null): ICarbonSealToken;
  waitForDeployment(): Promise<this>;

  interface: ICarbonSealTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  mintCredit: TypedContractMethod<
    [
      _to: AddressLike,
      _farmId: BigNumberish,
      _amount: BigNumberish,
      _methodology: string,
      _tokenURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "mintCredit"
  ): TypedContractMethod<
    [
      _to: AddressLike,
      _farmId: BigNumberish,
      _amount: BigNumberish,
      _methodology: string,
      _tokenURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
