/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CarbonSealRegistry } from "./CarbonSealRegistry";
export type { ICarbonSealToken } from "./ICarbonSealToken";
