/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carbonSealRegistrySol from "./CarbonSealRegistry.sol";
export type { carbonSealRegistrySol };
export type { CarbonSealOracle } from "./CarbonSealOracle";
