/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICarbonSealToken,
  ICarbonSealTokenInterface,
} from "../../../contracts/CarbonSealRegistry.sol/ICarbonSealToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_farmId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_methodology",
        type: "string",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "mintCredit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICarbonSealToken__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonSealTokenInterface {
    return new Interface(_abi) as ICarbonSealTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICarbonSealToken {
    return new Contract(address, _abi, runner) as unknown as ICarbonSealToken;
  }
}
