/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CarbonSealRegistry__factory } from "./CarbonSealRegistry__factory";
export { ICarbonSealToken__factory } from "./ICarbonSealToken__factory";
